name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        image:
          - name: latest
            python_version: "3.10"
          - name: python3.10
            python_version: "3.10"
          - name: python3.10-slim
            python_version: "3.10"
      fail-fast: true
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.image.python_version }}
      - name: Install Dependencies
        run: python -m pip install docker pytest
      - name: Deploy Image
        run: bash scripts/build-push.sh
        env:
          NAME: ${{ matrix.image.name }}
          PYTHON_VERSION: ${{ matrix.image.python_version }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
